# server port
server:
  port: 8080
  servlet:
    context-path: /xinguan/api
spring:
  datasource:
    url: jdbc:mysql://192.168.43.197:3306/pandemic?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true

    username: root
    password: bonjouroumar200
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.43.197
    port: 6379
#    database: 1
#    password: qkm19981013

# Swagger2 UI switch
# 地址一：swagger-ui.html
# 地址二：doc.html
swagger:
  enable: true

alioss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4GApsn3J85bSHEAcPCRb
  accessKeySecret: D5FfJRgZ0QhhyCqrqCneM55q7XCOoI
  bucketName: qkm-oss-test
  urlPrefix: https://qkm-oss-test.oss-cn-shenzhen.aliyuncs.com/
# 疫情数据网址
yq:
  dataUrl: https://zaixianke.com/yq/all

druid:
  username: admin
  password: admin

token:
  head: Authorization
  # token 有效期 1 天，单位分钟
  expireTime: 86400
  secret: ^_^.[IamQiuKangming].^_^

site:
  host: 192.168.43.197

# mybatis plus configuration
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.qkm.xinguan.domain.entity

app:
  author: Peppa-qiu
